name: Tests
on:
  push:
  pull_request:
  # workflow_dispatch:
  #   inputs:
  #     environment:
  #       description: "Choose an environment to deploy to: <dev|staging|prod>"
  #       required: true
  #       default: "dev"

jobs:

  # Linting and Unit Testing --------------------------
  # Only run during pushes (not pull-requests)
  lint_unit:
    name: Run Lint and Unit Tests
    if: github.event_name == 'push'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Use Node.js 20.10.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.10.0
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install && pnpm exec svelte-kit sync
    - name: Run lint
      run: pnpm run lint
    - name: Run unit tests
      run: pnpm run test

  # End to End Testing --------------------------------
  # Only run during pull requests
  e2e:
    name: Run End-To-End Testing
    if: |
      github.event_name == 'pull_request'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    # github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Use Node.js 20.10.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.10.0
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install && pnpm exec svelte-kit sync
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: pnpm exec playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  # Deploy --------------------------------------------
  # Run for every push, pull request, or event dispatch
  # https://github.com/cloudflare/wrangler-action
  deploy:
    name: Deploy to Cloudflare Pages
    needs: [e2e, lint_unit]
    if: |
      always() &&
      (needs.lint_unit.result == 'success' || needs.lint_unit.result == 'skipped') &&
      (needs.e2e.result == 'success' || needs.e2e.result == 'skipped')
    environment:
      # https://github.com/orgs/community/discussions/56123
      name: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Preview' }}
      # https://stackoverflow.com/questions/67385568/github-actions-how-to-dynamically-set-environment-url-based-on-deployment-step
      url: ${{ steps.deploy.outputs.deployment-url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 20.10.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install && pnpm exec svelte-kit sync
      - name: Build
        run: pnpm run build
      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: pnpm
          command: pages deploy .svelte-kit/cloudflare --project-name=portfolio
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: build
          path: .svelte-kit/cloudflare
          retention-days: 30
